# Generated by Django 5.0.3 on 2024-05-06 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_carouselimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarouselImage',
        ),
    ]
